#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 10 14:10:58 2020

@author: jvh

This script takes all .pq files in current directory with a given leading string (as assigned
from GridPopGPU), fuses them into a single file, and deposits that file into PQFiles subdirectory
Assumes that there are only 4 data columns, so 'shallow' grid type
                                                                                  
"""

import pandas as pd
import pyarrow.parquet as pq
import glob
from pathlib import Path

def pq_list(leading_string):
    """
    Looks in current directory for all .pq files with leading string,
    returns those files
    
    Parameters
    ----------
    grid_leading_string : string
        File name leading string as generated by GridPopGPU to call

    Returns
    -------
    List of .pq files that will be combined into a single file
    
    """
    
    file_list = glob.glob(leading_string + '*.pq')
    return file_list

def join_pq(file_list,
            leading_string):
    """
    Opens first .pq file in file_list and creates pandas frame
    Renames columns with file name (minus leading string) appended to ASO/POS/NEG/POL
    Opens all other .pq files and appends them to original frame, with renaming of columns
    Returns full sized frame
    Reads up to '-3' position so that '.pq' is cut out from names
    
    Parameters
    ----------
    file_list : list
        A list of file name strings that will be loaded and combined, generated by pq_list
    leading_string : string
        The file name leading string that identifies the file batch to be combined,
        as generated in GridPopGPU

    Returns
    -------
    List of .pq files that will be combined into a single file, with the columns named
    as calix_#_ASO, calix_#_POS, etc.
    
    """
    #Record length of leading string
    cutoff = len(leading_string)
    
    #Import and rename columns in first frame
    first_frame = pd.read_parquet(file_list[0])
    ff_aso_name = file_list[0][cutoff:-3] + "_ASO"
    ff_pol_name = file_list[0][cutoff:-3] + "_POL"
    ff_neg_name = file_list[0][cutoff:-3] + "_NEG"
    ff_pos_name = file_list[0][cutoff:-3] + "_POS"
    first_frame.rename(columns = {'ASO':ff_aso_name, 'POL':ff_pol_name,
                                  'NEG':ff_neg_name, 'POS':ff_pos_name}, inplace = True)
    
    #Import and append from each file in directory
    for file_name in file_list[1:]:
        add_frame = pd.read_parquet(file_name)
        add_aso_name = file_name[cutoff:-3] + "_ASO"
        add_pol_name = file_name[cutoff:-3] + "_POL"
        add_neg_name = file_name[cutoff:-3] + "_NEG"        
        add_pos_name = file_name[cutoff:-3] + "_POS"
        
        first_frame.insert(3, add_aso_name, add_frame['ASO'])
        first_frame.insert(4, add_pol_name, add_frame['POL'])
        first_frame.insert(5, add_neg_name, add_frame['NEG'])
        first_frame.insert(6, add_pos_name, add_frame['POS'])
    
    return first_frame

def pq_shell(grid_leading_string):
    """
    Top script that takes in the leading string, generates the new combined
    frame, and then saves to the proper working directory.

    Parameters
    ----------
    grid_leading_string : string
        Leading part of file name, as generated by GridPopGPU, that will be
        searched for, combined, and saved into 'PQFiles' folder

    Returns
    -------
    None - but combined file is saved

    """
    
    file_list = pq_list(grid_leading_string)
    full_frame = join_pq(file_list, grid_leading_string)
    # save_path = Path('PQFiles')
    save_string = grid_leading_string + 'Comb.pq'
    # full_frame.to_parquet(save_path / save_string)
    full_frame.to_parquet(save_string)

# pq_shell('AlokThesis10A_')
