#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 10 14:10:58 2020

@author: jvh

This script takes all .pq files in current directory with a given leading string (as assigned
from GridPopGPU), fuses them into a single file, and deposits that file into PQFiles subdirectory
Assumes that there are only 4 data columns, so 'shallow' grid type
                                                                                  
"""

import pandas as pd
import pyarrow.parquet as pq
import glob
from pathlib import Path

def pq_list(leading_string):
    """
    Looks in current directory for all .pq files with leading string,
    returns those files
    
    Parameters
    ----------
    grid_leading_string : string
        File name leading string as generated by GridPopGPU to call

    Returns
    -------
    List of .pq files that will be combined into a single file
    
    """
    
    file_list = glob.glob(leading_string + '*.pq')
    return file_list

def join_pq(file_list,
            leading_string):
    """
    Opens first .pq file in file_list and creates pandas frame
    Renames columns with file name (minus leading string) appended to ASO/POS/NEG/POL
    Opens all other .pq files and appends them to original frame, with renaming of columns
    Returns full sized frame
    Reads up to '-3' position so that '.pq' is cut out from names
    
    Parameters
    ----------
    file_list : list
        A list of file name strings that will be loaded and combined, generated by pq_list
    leading_string : string
        The file name leading string that identifies the file batch to be combined,
        as generated in GridPopGPU

    Returns
    -------
    List of .pq files that will be combined into a single file, with the columns named
    as calix_#_ASO, calix_#_POS, etc.
    
    """
    #Record length of leading string
    cutoff = len(leading_string)
    
    #Import and rename columns in first frame
    first_frame = pd.read_parquet(file_list[0])
    ff_aso_name = file_list[0][cutoff:-3] + "_ASO"
    ff_pol_name = file_list[0][cutoff:-3] + "_POL"
    ff_neg_name = file_list[0][cutoff:-3] + "_NEG"
    ff_pos_name = file_list[0][cutoff:-3] + "_POS"
    first_frame.rename(columns = {'ASO':ff_aso_name, 'POL':ff_pol_name,
                                  'NEG':ff_neg_name, 'POS':ff_pos_name}, inplace = True)
    
    #Import and append from each file in directory
    for file_name in file_list[1:]:
        add_frame = pd.read_parquet(file_name)
        add_aso_name = file_name[cutoff:-3] + "_ASO"
        add_pol_name = file_name[cutoff:-3] + "_POL"
        add_neg_name = file_name[cutoff:-3] + "_NEG"        
        add_pos_name = file_name[cutoff:-3] + "_POS"
        
        first_frame.insert(3, add_aso_name, add_frame['ASO'])
        first_frame.insert(4, add_pol_name, add_frame['POL'])
        first_frame.insert(5, add_neg_name, add_frame['NEG'])
        first_frame.insert(6, add_pos_name, add_frame['POS'])
    
    return first_frame

def extend_pq(existing_file,
              new_file_list,
              leading_string,
              aso_norm_val,
              pol_norm_val,
              pos_norm_val,
              neg_norm_val):
    """
    A function that takes an existing .pq file with many calixarenes,
    and extends it by the .pq files in new_file_list

    Parameters
    ----------
    existing_file : string
        Name of the .pq file that contains the already populated calixarene data
    new_file_list : list
        A list of file name strings that will be loaded and appended
    leading_string : string
        Name of the common beginning to the .pq file names to be appended
    aso_norm_val : float
        Amount to normalize ASO values by (to make new entries match original normalization)
    pol_norm_val : float
        Amount to normalize POL values by (to make new entries match original normalization)
    pos_norm_val : float
        Amount to normalize POS values by (to make new entries match original normalization)
    neg_norm_val : float
        Amount to normalize NEG values by (to make new entries match original normalization)

    Returns
    -------
    A new dataframe that has the additional calixarenes appended

    """

    starting_frame = pd.read_parquet(existing_file)
    
    #0.5A dataframes need the rows re-indexed to match appended parquet files
    
    starting_frame.reset_index(drop=True, inplace=True)
    
    cutoff = len(leading_string)
    
   
    #Import and append from each file in directory
    for file_name in new_file_list:
        add_frame = pd.read_parquet(file_name)
        add_aso_name = file_name[cutoff:-3] + "_ASO"
        add_pol_name = file_name[cutoff:-3] + "_POL"
        add_neg_name = file_name[cutoff:-3] + "_NEG"        
        add_pos_name = file_name[cutoff:-3] + "_POS"
        
       
        add_frame['ASO'] = add_frame['ASO'] / aso_norm_val
        add_frame['POL'] = add_frame['POL'] / pol_norm_val
        add_frame['NEG'] = add_frame['NEG'] / neg_norm_val
        add_frame['POS'] = add_frame['POS'] / pos_norm_val
        
       
        starting_frame.insert(3, add_aso_name, add_frame['ASO'])
        starting_frame.insert(4, add_pol_name, add_frame['POL'])
        starting_frame.insert(5, add_neg_name, add_frame['NEG'])
        starting_frame.insert(6, add_pos_name, add_frame['POS'])
    
    
    return starting_frame


def pq_shell(grid_leading_string):
    """
    Top script that takes in the leading string, generates the new combined
    frame, and then saves to the proper working directory.

    Parameters
    ----------
    grid_leading_string : string
        Leading part of file name, as generated by GridPopGPU, that will be
        searched for, combined, and saved into 'PQFiles' folder

    Returns
    -------
    None - but combined file is saved

    """
    
    file_list = pq_list(grid_leading_string)
    full_frame = join_pq(file_list, grid_leading_string)
    save_path = Path('.')
    save_string = grid_leading_string + 'Comb.pq'
    full_frame.to_parquet(save_path / save_string)

    return
    
def extend_existing_frame(pop_file_name,
                          leading_string,
                          new_file_name,
                          aso_norm_val,
                          pol_norm_val,
                          pos_norm_val,
                          neg_norm_val):
    """
    Top script that takes in a leading string, and the name of an existing .pq file
    with calixarene data. Creates a new .pq file with additional calixarenes (identified
    with leading string) appended, and saved with new_file_name

    Parameters
    ----------
    pop_file_name : string
        Name of the existing .pq file to be appended
    leading_string : string
        Common name beginning shared by .pq files
    new_file_name : string
        Name with which to save the extended .pq file

    Returns
    -------
    None, but saves the desired extended .pq file

    """

    file_list = pq_list(leading_string)
    file_list.remove(pop_file_name)
    full_frame = extend_pq(pop_file_name,
                           file_list,
                           leading_string,
                           aso_norm_val,
                           pol_norm_val,
                           pos_norm_val,
                           neg_norm_val)
    full_frame.to_parquet(new_file_name)
    
    return

def drop_calixarenes(pop_file_name,
                     calix_name_list,
                     new_file_name):
    """
    Function that removes calixarenes from an existing dataframe
    Currently assumes that there are 4 conformer searches per dataframe and
    4 color channel inputs (ASO, POL, NEG, POS)

    Parameters
    ----------
    pop_file_name : string
        Name of calixarene to open for processing
    calix_name_list : list
        A list of calixarene prefixes that will be dropped from the file
    new_file_name : string
        New file name to save dataframe as

    Returns
    -------
    None, but saves the desired modified .pq file

    """

    starting_frame = pd.read_parquet(pop_file_name)
    
    for calix_name in calix_name_list:
        for conformer in range(4):
            this_col = calix_name + '_' + str(conformer + 1)
            this_col_aso = this_col + '_ASO'
            this_col_pol = this_col + '_POL'
            this_col_neg = this_col + '_NEG'
            this_col_pos = this_col + '_POS'
            
            starting_frame.drop(this_col_aso, inplace=True, axis=1)
            starting_frame.drop(this_col_pol, inplace=True, axis=1)
            starting_frame.drop(this_col_neg, inplace=True, axis=1)
            starting_frame.drop(this_col_pos, inplace=True, axis=1)

    starting_frame.to_parquet(new_file_name)
    
    return

# pq_shell('50C_Boltz2_Iso_')